### ISSUE TITLE
Update the README.md file

### ISSUE THREAD

**Issue by amaze560** [kritan560/shadcn-onborda-nextjs#5]
### Description:
The current README.md file does not provide sufficient information for developers and users to understand and contribute to the project effectively. It lacks key details and instructions that are critical for setting up, using, and contributing to the project.

**Issues Identified:**
- **Incomplete Setup Instructions:**
        The existing README does not fully explain how to set up the project locally. There are missing steps that could lead to confusion for new developers.

- **Lack of Usage Examples:**
        There are no examples or guides on how to use the features of the project. This makes it difficult for users to understand the functionality and capabilities..

**Comment by kritan560** [comment]
Yes the readme is old thanks for letting us know about it we will soon comply with the query you made
